### PR TITLE
Test pedantically. Fix all warnings.

### PR DESCRIPTION
**Pull request by cblp**

### CODE REVIEW

**Comment by klappvisor** [comment]
Thank you for contribution! not sure about renaming in tests, but the rest is highly appreciated

**Comment by cblp** [comment]
Renaming is needed to fix name shadowing

**Comment by klappvisor** [comment]
I see, not sure it's so critical for tests. anyway, I will merge it soon, don't bother fixing conflicts

**Comment by klappvisor** [comment]
merged, pedantic build helped couple of times already!

**Comment by cblp** [comment]
thanks!

**Comment by cblp** [comment]
hm, `stack test --pedantic` still show errors in tests

**Comment by cblp** [comment]
> I see, not sure it's so critical for tests.

I don't see why tests code should be less quality than other.

**Comment by klappvisor** [comment]
0 warnings in tests of course are desirable, but I would not sacrifice readability and rename variables just to fix shadowing. 
I agree test code should be the same quality as the main one, unless it's conscious decision to ignore some warnings has been made because they don't bring value.

At the same time treating warnings as errors is very valuable in main code. for instance ` Defined but not used` warning shows me that I forgot to export data type and build should definitely fail since data type is not usable.

**Pull request merged**
