### PR TITLE
`getUpdates` must accept parameters

### PR DESCRIPTION
**Pull request by cblp**
This change is [Reviewable](https://reviewable.io/reviews/klappvisor/haskell-telegram-api/88)

### CODE REVIEW

**Comment by klappvisor** [comment]
to me it looks like export `getUpdatesM'` (that accepts `GetUpdatesRequest`) would be enough

**Comment by cblp** [comment]
But current _getUpdatesM_ is too trivial, it is not useful without any parameters. But if user wants, they can just call _getUpdates getUpdatesRequest_.

**Comment by klappvisor** [comment]
yes, it is for simple use. so `getUpdatesM'` can be used (once exported) for more complex use cases, but I see your point. tbh now after thinking about it more I would swap methods with prime and without it to have `getUpdatesM` that accept request and prime version that does not. but my concern is again backward compatibility. it's already not so good, will it make it worse?

**Comment by cblp** [comment]
I think any solution of these is good.

**Pull request merged**
