### PR TITLE
Add command line option parsing with optparser-applicative to tests

### PR DESCRIPTION
**Pull request by Arguggi**
Now it is possibile to also use the hspec options.

### CODE REVIEW

**Comment by klappvisor** [comment]
Nice improvement

**Comment by Arguggi** [comment]
Not sure why circleci is failing though.

**Comment by Arguggi** [comment]
My build failed since circleci won't export your environment variables when the build is started by a fork. I added the necessary variables to my circleci account, hopefully the tests run now.

**Comment by klappvisor** [comment]
Since we have not really unit test per se but more integration test which needs to be querying teal Telegram API, I would skip tests when there are no parameters specified. At least it's current behavior.

**Comment by klappvisor** [comment]
> Did you change anything to make stack work on circleci?

@Arguggi no, I don't remember I had to do anything special...

**Comment by Arguggi** [comment]
I added a quick hack to make it work.
It only checks if 3 arguments are passed. I think it's better to show the help text and exit with failure when the arguments are wrong (like when no arguments are actually passed) and only exit with success when there are 3 arguments. It seems an unlikely enough scenario (since --options require an actual option after and there are no switches).

**Pull request merged**
